# Imports

In [1]:
import datetime
import tweepy
import pandas as pd
import re
import json
import time

# Load Query CSV
- Jacob: jacob.csv
- Winston: winston.csv
- Niyi: niyi.csv

In [17]:
# Replace your name here in lowercase with the one that matches your csv
name = ''

In [18]:
csv = 'Queries/'+ name + '_queries.csv'

In [19]:
query_df = pd.read_csv(csv)
query_df['Query'] = query_df['Query'].apply(lambda x: x.strip())
query_df['Date'] = query_df['Date'].apply(lambda x: x.strip())
query_df

                                                Query        Date
0                                      Twitter Launch  07/15/2006
1    Trans-Atlantic OR transatlantic (Terrorist Plot)  08/10/2006
2                             Iran (Nuclear Standoff)  08/31/2006
3                                 Steve Irwin (Death)  09/04/2006
4                          North Korea (Nuclear Test)  10/09/2006
5                               Yankees (Plane Crash)  10/11/2006
6                    Ted Haggard (Megachurch Scandal)  11/04/2006
7                 Saddam Hussein (Sentenced to death)  11/05/2006
8   Democrats (Win midterms and control house and ...  11/07/2006
9                                 iPhone (Introduced)  01/09/2007
10         North Korea Nuclear Facilities (Shut Down)  02/13/2007
11                      New Horizons (Jupiter Photos)  02/28/2007
12                             Virginia Tech Shooting  04/16/2007
13                          iPhone release (Released)  06/29/2007
14                Nasa (Launches Phoenix Mars Lander)  08/04/2007
15  Israeli Airforce Syria (attack suspected nucle...  09/06/2007
16           WikiLeaks Guantanamo Bay (Protocol Leak)  11/07/2007
17  Benazir Bhutto (Pakistani Prime Minister assas...  12/27/2007
18                                Stock Market Plunge  01/14/2008
19    WikiLeaks Julius Baer (Illegal Activities Leak)  02/18/2008
20               Manchester United European Cup (Win)  05/21/2008
21            Phoenix Mars (Spacecraft lands on mars)  05/25/2008
22  Barack Obama (Selection for Democratic Candidate)  06/03/2008
23               Lehman Brothers (Declare Bankruptcy)  09/15/2008
24                      SpaceX Falcon 1 (Makes orbit)  09/28/2008
25                                 Android (Released)  09/23/2008
26                     Barack Obama (Wins Presidency)  11/04/2008
27                            Bitcoin (Genesis block)  01/03/2008
28               Barack Obama (Inaugurated President)  01/20/2009
29               General Motors (Declares Bankruptcy)  06/01/2009
30                    H1N1 (Declared Global Pandemic)  06/11/2009
31                                      Solar Eclipse  07/22/2009
32      H1N1 Vaccine (China Completes Clinical Trial)  09/21/2009
33                         Call of Duty (MW2 Release)  11/10/2009
34                       Afghanistan (US Troop Surge)  12/01/2009
35      Avatar (Movie Release Highest grossing movie)  12/18/2009
36                   Burj Khalifa (Tallest Structure)  01/04/2010
37                                   Haiti Earthquake  01/12/2010
38                         Winter Olympics (Complete)  02/28/2010
39                       Affordable Care Act (Passed)  03/20/2010
40                      Deepwater Horizon (Oil Spill)  04/20/2010
41         Flash Crash (36-minute stock market crash)  05/06/2010
42                                          World Cup  07/11/2010
43              H1N1 WHO (WHO Declares Pandemic Over)  08/10/2010
44                        US Troops Iraq (Leave Iraq)  08/30/2010
45                                   Japan Earthquake  03/15/2011
46                   Wikileaks Guantanamo (2011 leak)  04/24/2011
47                                 Bin Laden (Killed)  05/02/2011
48                                 Occupy Wall Street  09/19/2011
49                                   Gaddafi (Killed)  10/20/2011

In [20]:
format_str = '%m/%d/%Y'

In [21]:
query_df['Query'] = query_df['Query'].apply(lambda x: re.sub("[\(\[].*?[\)\]]", "", x)) 
query_df['From_Date'] = query_df['Date'].apply(lambda date_str: datetime.datetime.strptime(date_str, format_str))
query_df['To_Date'] = query_df['From_Date'].apply(lambda date_obj: date_obj + pd.Timedelta(1, 'days'))

In [22]:
query_df['From_Date'] = query_df['From_Date'].apply(lambda x: x.strftime("%Y%m%d%H%M"))
query_df['To_Date'] = query_df['To_Date'].apply(lambda x: x.strftime("%Y%m%d%H%M"))

Verify Query Dataframe is in order

In [23]:
query_df

                               Query        Date     From_Date       To_Date
0                     Twitter Launch  07/15/2006  200607150000  200607160000
1   Trans-Atlantic OR transatlantic   08/10/2006  200608100000  200608110000
2                              Iran   08/31/2006  200608310000  200609010000
3                       Steve Irwin   09/04/2006  200609040000  200609050000
4                       North Korea   10/09/2006  200610090000  200610100000
5                           Yankees   10/11/2006  200610110000  200610120000
6                       Ted Haggard   11/04/2006  200611040000  200611050000
7                    Saddam Hussein   11/05/2006  200611050000  200611060000
8                         Democrats   11/07/2006  200611070000  200611080000
9                            iPhone   01/09/2007  200701090000  200701100000
10   North Korea Nuclear Facilities   02/13/2007  200702130000  200702140000
11                     New Horizons   02/28/2007  200702280000  200703010000
12            Virginia Tech Shooting  04/16/2007  200704160000  200704170000
13                   iPhone release   06/29/2007  200706290000  200706300000
14                             Nasa   08/04/2007  200708040000  200708050000
15           Israeli Airforce Syria   09/06/2007  200709060000  200709070000
16         WikiLeaks Guantanamo Bay   11/07/2007  200711070000  200711080000
17                   Benazir Bhutto   12/27/2007  200712270000  200712280000
18               Stock Market Plunge  01/14/2008  200801140000  200801150000
19            WikiLeaks Julius Baer   02/18/2008  200802180000  200802190000
20   Manchester United European Cup   05/21/2008  200805210000  200805220000
21                     Phoenix Mars   05/25/2008  200805250000  200805260000
22                     Barack Obama   06/03/2008  200806030000  200806040000
23                  Lehman Brothers   09/15/2008  200809150000  200809160000
24                  SpaceX Falcon 1   09/28/2008  200809280000  200809290000
25                          Android   09/23/2008  200809230000  200809240000
26                     Barack Obama   11/04/2008  200811040000  200811050000
27                          Bitcoin   01/03/2008  200801030000  200801040000
28                     Barack Obama   01/20/2009  200901200000  200901210000
29                   General Motors   06/01/2009  200906010000  200906020000
30                             H1N1   06/11/2009  200906110000  200906120000
31                     Solar Eclipse  07/22/2009  200907220000  200907230000
32                     H1N1 Vaccine   09/21/2009  200909210000  200909220000
33                     Call of Duty   11/10/2009  200911100000  200911110000
34                      Afghanistan   12/01/2009  200912010000  200912020000
35                           Avatar   12/18/2009  200912180000  200912190000
36                     Burj Khalifa   01/04/2010  201001040000  201001050000
37                  Haiti Earthquake  01/12/2010  201001120000  201001130000
38                  Winter Olympics   02/28/2010  201002280000  201003010000
39              Affordable Care Act   03/20/2010  201003200000  201003210000
40                Deepwater Horizon   04/20/2010  201004200000  201004210000
41                      Flash Crash   05/06/2010  201005060000  201005070000
42                         World Cup  07/11/2010  201007110000  201007120000
43                         H1N1 WHO   08/10/2010  201008100000  201008110000
44                   US Troops Iraq   08/30/2010  201008300000  201008310000
45                  Japan Earthquake  03/15/2011  201103150000  201103160000
46             Wikileaks Guantanamo   04/24/2011  201104240000  201104250000
47                        Bin Laden   05/02/2011  201105020000  201105030000
48                Occupy Wall Street  09/19/2011  201109190000  201109200000
49                          Gaddafi   10/20/2011  201110200000  201110210000

# Search Tweets
Saved Documentation:
- https://developer.twitter.com/en/docs/twitter-api/enterprise/rules-and-filtering/operators-by-product
- twitter.com/anyuser/status/tweet_id allows searching for tweets by tweet id

In [9]:
# Construct the API instance
# Replace these with your API Key and API Secret Key
api_key = 'REPLACE'
api_secret_key = 'REPLACE'
auth = tweepy.AppAuthHandler(api_key, api_secret_key)
tweepy_api = tweepy.API(auth)

In [10]:
# Replace this label with the dev envrioment label you created for the full archive search
dev_environment_label = 'REPLACE'
query_operators = 'lang:en'

In [11]:
# This list holds the tweets search by tweepy
tweet_json_list = []

In [34]:
# Loop over each query and append the output to the list
for i in range(40, len(query_df)):
    # Wait for rate limit to refresh half way through searching queries
    if i == 25:
        time.sleep(120)
    returned_tweets = tweepy_api.search_full_archive(dev_environment_label, query_df['Query'][i] + ' ' + query_operators, fromDate=query_df['From_Date'][i], toDate=query_df['To_Date'][i], maxResults=100)
    for tweet in returned_tweets:
        tweet_json_list.append(tweet._json)

In [35]:
len(tweet_json_list)

2785

# Save Tweets

In [36]:
def writeToJSONFile(path, fileName, data):
    try:
        filePathNameWExt = path + fileName
        with open(filePathNameWExt, 'w') as fp:
            json.dump(data, fp)
    except Exception as e:
        if(not quiet):
            print("writeToJSONFile exception")
            print(e)

In [37]:
writeToJSONFile('Data/', name + '_tweets.json', tweet_json_list)

In [38]:
with open('Data/' + name + '_tweets.json') as json_data:
    tweets_json_from_file = json.load(json_data)

Verify Tweets list and saved json file contain the same Tweets

In [39]:
len(tweet_json_list) == len(tweets_json_from_file)

True

In [40]:
tweet_json_list == tweets_json_from_file

True